export const REDUCER_NAME = 'exchange'

export const GET_ALL_CURRENCIES_START = 'GET_ALL_CURRENCIES_START'
export const GET_ALL_CURRENCIES_SUCCESS = 'GET_ALL_CURRENCIES_SUCCESS'
export const GET_ALL_CURRENCIES_FAILURE = 'GET_ALL_CURRENCIES_FAILURE'

export const GET_EXCHANGE_AMOUNT_START = 'GET_EXCHANGE_AMOUNT_START'
export const GET_EXCHANGE_AMOUNT_SUCCESS = 'GET_EXCHANGE_AMOUNT_SUCCESS'
export const GET_EXCHANGE_AMOUNT_FAILURE = 'GET_EXCHANGE_AMOUNT_FAILURE'

export const GET_ESTIMATED_EXCHANGE_AMOUNT_START = 'GET_ESTIMATED_EXCHANGE_AMOUNT_START'
export const GET_ESTIMATED_EXCHANGE_AMOUNT_SUCCESS = 'GET_ESTIMATED_EXCHANGE_AMOUNT_SUCCESS'
export const GET_ESTIMATED_EXCHANGE_AMOUNT_FAILURE = 'GET_ESTIMATED_EXCHANGE_AMOUNT_FAILURE'
